# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(db_index=True, max_length=200)),
                ('article_content', models.TextField()),
                ('article_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Genre'),
        ),
    ]
