# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('contact_email', models.EmailField(max_length=254)),
                ('email_copy', models.BooleanField(default=False)),
                ('email_content', models.TextField()),
                ('contact_date', models.DateTimeField(verbose_name='contact_date')),
            ],
        ),
    ]
