# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=140)),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_first', models.CharField(max_length=50)),
                ('user_last', models.CharField(max_length=50)),
                ('comment_content', models.CharField(max_length=500)),
                ('aprprt_comment', models.BooleanField(default=False)),
                ('comment_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=500)),
                ('post_date', models.DateField(verbose_name='published_on')),
                ('post_tile', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_pub_date', models.DateField(verbose_name='published_on')),
                ('song_description', models.CharField(max_length=200)),
                ('song_rating', models.FloatField(default=0.0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Album')),
                ('song_artist', models.ManyToManyField(to='media.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_pub_date', models.DateField(verbose_name='published_on')),
                ('video_description', models.CharField(max_length=200)),
                ('video_rating', models.FloatField(default=0.0)),
                ('video_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Artist'),
        ),
    ]
